chore: make each project package's lint script runnable
Add a .eslintrc file to each package in the packages directory. Each such file only references the main eslintrc.

Add eslint-config-prettier and upgrade eslint-plugin-prettier.

It is now possible to run each of these packages' lint script. For example:

```
cd packages/a11y && yarn run lint
yarn run v1.22.18
$ dts lint
Defaulting to "dts lint src"
You can override this in the package.json scripts, like "lint": "dts lint src otherDir"

✨  Done in 5.12s.
```

This would previously crash:

```
$ cd packages/a11y && yarn run lint
> @entur/a11y@0.2.46 lint /Users/eirikvageskar/design-system/packages/a11y
> dts lint

Defaulting to "dts lint src"
You can override this in the package.json scripts, like "lint": "dts lint src otherDir"
Error: Failed to load config "prettier" to extend from.
Referenced from: BaseConfig
    at configInvalidError (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2596:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3189:23)
    at ConfigArrayFactory._loadExtends (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3087:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3026:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2971:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.create (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2766:16)
    at createBaseConfigArray (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3491:48)
    at new CascadingConfigArrayFactory (/Users/eirikvageskar/design-system/node_modules/dts-cli/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3627:30) {
  messageTemplate: 'extend-config-missing',
  messageData: { configName: 'prettier', importerName: '' }
}
```

affects: @entur/a11y, @entur/alert, @entur/button, @entur/chip, @entur/datepicker, @entur/dropdown,
@entur/expand, @entur/fileupload, @entur/form, @entur/grid, @entur/icons, @entur/layout,
@entur/loader, @entur/menu, @entur/modal, @entur/tab, @entur/table, @entur/tokens, @entur/tooltip,
@entur/travel, @entur/typography, @entur/utils